dagger/container-use

README.md

Personally, I missed the fact that the titles were hyper-linked until I started to edit the README, adding a little more explicit instructions to help people understand what they need to do.

Improve the VS Code + Copilot instructions a little.

---

Makefile
README.md
hack/build.sh
hack/install.sh
hack/uninstall.sh

On top of #22
This will provide more targeted guidance when calling `make install`.
Specifically:
- If installation is successful, tell the user they may need to run hash -r
- If the install destination is not in PATH, tell the user how to add it.
- If the install destination is in PATH but has lower precedence than an already
existing binary (such as /usr/bin/cu on macOS) then tell the user how to update
their PATH accordingly.
Also, I moved most of the Makefile logic into hack scripts.

make: better install messages regarding PATH

---

Makefile
hack/build.sh

`make install` is broken:
- missing dependency on building the cu binary when on the install target
- `build.sh` script had a typo

fix: Makefile

---

cmd/cu/log.go
cmd/cu/logger.go

Related to issue #50.
I want to ignore that there is a remote-local fork under `~/.config`. So I should be able to show the local env, without having to know where it lives on the disk or understand there are 2 forks (mine and cu's).

cmd/cu: adds show command to help with git show <remote branch>

---

cmd/cu/version.go

useless for `go run` builds, but GoReleaser sets 
```
ldflags:
- -s -w
- -X main.version={{.Version}}
- -X main.commit={{.Commit}}
- -X main.date={{.Date}}
```
that will help us help folks debug.
I also added debug.ReadBuildInfo logic for `go build` based dev builds.

add cu version command

---

README.md

Fixes #21
Uses [Cursor deeplink](https://docs.cursor.com/deeplinks) for one-click install.

Adds README instructions for Cursor

---

.dagger/main.go
.github/workflows/release.yml
.goreleaser.yaml
README.md
RELEASING.md

**NOTE**: this requires that we configure a token that has Content and PR R/W permissions on container-use and homebrew-tap repos. I do not have the powers, but there's a pending one called `release-container-use` that has the right stuff. I also don't think I have the right permissions to configure that on GHA unless they moved the button on me.
I've tested this works by forking dagger's org level homebrew tap. 
`brew install cwlbraa/homebrew-tap/container-use` should work for you, too. It overrides MacOS's quarantine thing.
TODO:

Release to homebrew

---

.goreleaser.yaml

the previous configuration "worked" by pushing to homebrew-tap/main but didn't open a PR. As a consequence, the automation created a window where the brew tap is published but the release it points at is not. 
this PR fixes the configuration to explicitly provide a `base` and a the token we passed in.

ci: fix PR to homebrew tap flow

---

.goreleaser.yaml

this is my last push and pray attempt. upon closer inspection of the goreleaser docs instead of just the yaml schema, the issue here was that we were opening a PR from main onto main. 
https://goreleaser.com/customization/homebrew_casks/
```yaml
pr:
```
if this doesn't work I'll set up my fork-oriented testing again, it's just a bit of a hassle.

ci: fix brew tap PR goreleaser configuration

---

README.md

Adds a video link to the VS Code setup and walkthrough.

docs: Add video link to VS Code setup

---

cmd/cu/delete.go
cmd/cu/log.go
cmd/cu/merge.go
cmd/cu/watch.go
repository/git.go
repository/repository.go

- Use the "git root" as the base directory
- Add sanity checks to ensure we're running from a git repo, clear error
message if not.
- Make sure all commands go through `repository.Open()` to ensure sanity
checks are being run.

cli: sanity checks and cleanup

---

environment/filesystem.go
environment/service.go
repository/repository.go

The [`Repository.Update()`](https://github.com/dagger/container-use/blob/main/repository/repository.go#L147) method was causing the application to hang when called from tool handlers that don't add notes to the environment. This happened because:
1. [`repo.Update()`](https://github.com/dagger/container-use/blob/main/repository/repository.go#L147) calls [`env.Notes.Pop()`](https://github.com/dagger/container-use/blob/main/environment/note.go#35) to get a note message.
2. When no notes were added, `Pop()` returns an empty string.
3. ⚠️ the `git notes --ref container-use append -m ""` command behaves differently depending on Git version ([reference](https://stackoverflow.com/a/76633969)):
* On **Git versions (>= 2.42, < [2.47 batch 3](https://github.com/git/git/commit/25673b1c476756ec0587fb05 …

Fix: Prevent git notes command hanging when no environment notes exist

---

repository/git.go
repository/repository.go

`touch .gitkeep` and really any `touch` command creates a weird state where the file might exist and show up in `git status` but not be committed.
also a few renames for clarity and fixed `modernize splitseq` linter.

fix empty file committing & modernize splitseq

---

cmd/cu/list.go
environment/environment.go
mcpserver/tools.go
repository/git.go
repository/repository.go

The environment name was used to easily recognize environments. Since
now they have a full blown description, it's not needed anymore.
DEPENDS ON #107

remove environment names

---

README.md

New users might not know that they need to manually accept the permissions before they can run `claude --dangerously-skip-permissions` as part of a piped command.
[Related comment](https://github.com/dagger/container-use/pull/40#issuecomment-2993538457)

docs: add a note about claude code permissions

---

cmd/cu/checkout.go
mcpserver/tools.go
repository/git.go
repository/repository.go
rules/agent.md
rules/cursor.mdc

- Do not set up remote tracking branches for each environment anymore
- Instead, provide an explicit `cu checkout` command that does that
- Similar to `gh pr checkout`
This still requires reworking the prompt engineering behind the scenes
DEPENDS ON #107

cu checkout

---

.goreleaser.yaml
README.md
install.sh
scripts/completions.sh

requires #130 
this PR installs shell completions using homebrew post install hooks and provides instructions on how to install them as install.sh output.
complexities:
- bash: there are canonical locations for bash, but those locations require the (very standard) [bash-completion](https://github.com/scop/bash-completion#q-where-should-i-install-my-own-local-completions) plugin.
- in homebrew, we'll just assume you have that package or if you're using bash over default zsh, you'll guess that you need it.
- zsh: there are no canonical locations, but you can look up locations from fpath if your shell is all configured (ohmyzsh, antigen, etc). 
- homebrew [documents](https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh) how things need to be set up for zsh completions, and so …

shell completion installs

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

this adds a bug report and feature request template to encourage folks to give us logs and `cu version` output, but leaves blank issues enabled for all the cases where tempplates generate annoying boilerplate.

add some optional issue templates for bug reporters

---

environment/config.go
environment/config_test.go
environment/environment.go

fixes #123 
previously we were returning early in the case where the instructions.md was missing but the user had provided the environment.json file. this fixes that bug and adds some unit tests.

Best effort env config loading

---

.github/ISSUE_TEMPLATE/bug_report.yml

not every bug needs the internal logs, just the mysterious ones

make logs optional in issue template

---

mcpserver/tools.go

de-duplicate response conversion code
We were missing `cu diff` in a couple of places, figured we should only do this once.

mcp: response marshalling cleanup

---

docs/agent-integrations.mdx

isolating the agent to just container-use is pretty powerful :) 
we will need to remember to update the docs when we add new tools, though, which is quite annoying, ntm users won't necessarily re-paste config later (or re-run `cu configure`)...

docs: add zed agent profile instructions

---

repository/git.go

Fixes a bug when running `cu diff <env>` in detached HEAD mode.

repository: handle detached HEAD

---

.goreleaser.yaml

missed this in the great rename. low prio, but will get tested in v0.2.1 release.

brew: cleanup cu on uninstall

---

go.mod
go.sum

this fixes cache misses in cu terminal for users with the newest dagger cli. 
`cu terminal` will upgrade your engine to 18.12, then the cu server will downgrade it, back and forth. each time, you get cache misses when the engine's been restarted.
https://discord.com/channels/707636530424053791/1392468264772440094

upgrade dagger to 18.12

---

.container-use/environment.json
.goosehints
AGENT.md
CLAUDE.md
cmd/container-use/agent/configure_test.go
cmd/container-use/config.go
docs/environment-configuration.mdx
environment/config.go
environment/config_test.go
environment/environment.go
environment/integration/helpers.go
environment/integration/integration_test.go
environment/service.go
environment/state.go
mcpserver/tools.go
repository/git.go

Experimental PR that moves the ownership of env config to the user.
1) Environment updates are ephemeral, the mcp tool will instruct the agent to inform the user to run `cu config` commands to make the changes persistent.
2) Separate `environment_config` (base image, setup commands) and `environment_update_metadata` (title) into 2 distinct tools.
3) Removed `instructions` from container-use -- updated our own repo to use CLAUDE.md and .goosehints

ephemeral config changes

---

docs/agent-integrations.mdx

To generate allowed tools in proper format:
```shell
echo '{"jsonrpc":"2.0", "method":"tools/list","id":1}' | container-use stdio | jq '{
permissions: {
allowed_tools: [
.result.tools[]
| select(.name | startswith("environment_"))
| "mcp_container-use_"+.name
]
}
}'
```
```json
"permissions": {
"allowed_tools": [
"mcp_container-use_environment_add_service",
"mcp_container-use_environment_checkpoint",
"mcp_container-use_environment_config",
"mcp_container-use_environment_create",
"mcp_container-use_environment_file_delete",
"mcp_container-use_environment_file_edit",
"mcp_container-use_environment_file_list",
"mcp_container-use_environment_file_read",
"mcp_container-use_environment_file_write",
"mcp_container-use_environment_open",
"mcp_container-use_environment_run_cmd", …
```

docs: charm crush agent plus update tool lists for new `file_edit` tool

---

environment/config_test.go

this test always fails on my machine, but passes in containers and in CI

fix permissions tests when not running as root

---

AGENT.md

the old ones included some extraneous parameters for initialization and didn't explain that you've gotta make /tmp/test-repo before doing manual testing.

better manual test instructions

---

.container-use/environment.json
AGENT.md

does what it says on the tin -- running `golangci-lint run` directly is way stricter than what we're running in CI and makes the agent generate large diffs when im just trying to get green checks.

chore: fix agent linter instructions so linter output matches CI

---

environment/integration/helpers.go
environment/integration/integration_test.go
environment/integration/repository_test.go
mcpserver/tools.go
repository/git.go
repository/repository.go

this makes it easier to multitask across multiple branches -- you can get the "base" source code from somewhere other than userLocalRepo HEAD meaning that you can change what you've got on HEAD and still safely restart chat sessions that have been prompted to start from a specific SHA. 
corollary to this, we should probably add extra arguments to `cu diff` so that `head` isn't always implied as the base of the diff we're showing... if we persisted this resolved sha, you could even ostensibly have a `--from-source-ref=true` flag that just shows you what the env has added since you started the env... that'd have different content compared to what you get from `cu apply`, so maybe not a good default, but not a bad option to have for best-of-N development.

feature: allow agent to specify a git ref for environment creation

---

environment/integration/integration_test.go
repository/flock.go
repository/git.go
repository/git_test.go
repository/repository.go

Previously we were holding the notes lock for the duration of `Repository.Update(env)`. This meant that running stuff like `cu diff` would block during env_run_cmd. 
This PR tightens that up a bit and makes `cu diff` feel instantaneous again in my testing.
I beat on this heavily using the Contention tests, running 2x5x10 both inside an env and on my host machine and it doesn't reintroduce any data races afaict.

avoid holding locks during Export

---

docs/agent-integrations.mdx

With the release of [Permissions](https://ampcode.com/news/tool-level-permissions) the `amp.commands.allowlist` and `amp.commands.strict` settings are gone.

docs: update Amp integration guide

---

dagger.json

Bug: the old dagger go module pin kept the Wolfi base image on protobuf~31, but the repo only serves protobuf 32.x now, so our build died while solving packages.
Fix: bump github.com/dagger/dagger/modules/go to ce291e358cf9e74f38f7c86972dc6478918513d7, which carries the protobuf~32 update and makes the pipeline green again.

chore(dagger): bump go module pin to fix Wolfi protobuf resolver
